site_name: Onnum Puriyala
site_url: https://ajax-y.github.io/documentation/
repo_url: https://github.com/ajax-y/documentation
use_directory_urls: true
theme:
  name: github
  favicon: img/favicon.ico
  features:
    - navigation.top.search_button.hide
    - revision.date
    - revision.history

plugins:
  - git-revision-date

extra:
  generator: false

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
