site_name: Onnum Puriyala
site_url: https://ajax-y.github.io/documentation/
repo_url: https://github.com/ajax-y/documentation
use_directory_urls: true
theme:
  name: material
  favicon: img/favicon.ico
  features:
    - navigation.top.search_button.hide
    - revision.date
    - revision.history
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

plugins: []

extra:
  generator: false

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
